%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('ExtensibilityElement', {anyAttribs, 'required'}).
-record('EndpointType', {anyAttribs, 'name', 'binding', 'address', 'documentation', choice}).
-record('ServiceType', {anyAttribs, 'name', 'interface', 'documentation', choice}).
-record('BindingFaultType', {anyAttribs, 'ref', 'documentation', choice}).
-record('BindingOperationFaultType', {anyAttribs, 'ref', 'messageLabel', 'documentation', choice}).
-record('BindingOperationMessageType', {anyAttribs, 'messageLabel', 'documentation', choice}).
-record('BindingOperationType-input', {anyAttribs, 'messageLabel', 'documentation', choice}).
-record('BindingOperationType-output', {anyAttribs, 'messageLabel', 'documentation', choice}).
-record('BindingOperationType-infault', {anyAttribs, 'ref', 'messageLabel', 'documentation', choice}).
-record('BindingOperationType-outfault', {anyAttribs, 'ref', 'messageLabel', 'documentation', choice}).
-record('BindingOperationType', {anyAttribs, 'ref', 'documentation', choice}).
-record('BindingType', {anyAttribs, 'name', 'type', 'interface', 'documentation', choice}).
-record('PropertyType-value', {anyAttribs, 'value'}).
-record('PropertyType-constraint', {anyAttribs, 'constraint'}).
-record('PropertyType', {anyAttribs, 'ref', 'documentation', choice, any}).
-record('FeatureType', {anyAttribs, 'ref', 'required', 'documentation', any}).
-record('InterfaceFaultType', {anyAttribs, 'name', 'element', 'documentation', choice}).
-record('MessageRefFaultType', {anyAttribs, 'ref', 'messageLabel', 'documentation', choice}).
-record('MessageRefType', {anyAttribs, 'messageLabel', 'element', 'documentation', choice}).
-record('InterfaceOperationType-input', {anyAttribs, 'messageLabel', 'element', 'documentation', choice}).
-record('InterfaceOperationType-output', {anyAttribs, 'messageLabel', 'element', 'documentation', choice}).
-record('InterfaceOperationType-infault', {anyAttribs, 'ref', 'messageLabel', 'documentation', choice}).
-record('InterfaceOperationType-outfault', {anyAttribs, 'ref', 'messageLabel', 'documentation', choice}).
-record('InterfaceOperationType', {anyAttribs, 'name', 'pattern', 'safe', 'style', 'documentation', choice}).
-record('InterfaceType', {anyAttribs, 'name', 'extends', 'styleDefault', 'documentation', choice}).
-record('TypesType', {anyAttribs, 'documentation', any}).
-record('IncludeType', {anyAttribs, 'location', 'documentation', any}).
-record('ImportType', {anyAttribs, 'namespace', 'location', 'documentation', any}).
-record('DescriptionType', {anyAttribs, 'targetNamespace', 'documentation', choice}).
-record('ExtensibleDocumentedType', {anyAttribs, 'documentation'}).
-record('DocumentedType', {anyAttribs, 'documentation'}).
-record('DocumentationType', {anyAttribs, choice}).
